version: '3.8'

services:
  db-dev: 
    image: postgres:15-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydbdev
    ports:
      - "5433:5432"
    networks:
      - net-dev

  backend-dev:
    image: ${REGISTRY_IP}:5000/backend:latest 
    container_name: backend-dev
    ports:
      - "3000:8080" 
    environment:
      - ENTORNO_NAME=DESARROLLO
      - DB_URL=jdbc:postgresql://db-dev:5432/mydbdev 
      - DB_USER=user
      - DB_PASS=password
    depends_on:
      - db-dev
    networks:
      - net-dev

  db-prod: 
    image: postgres:15-alpine
    container_name: postgres-prod
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: mydbprod
    ports:
      - "5434:5432"
    networks:
      - net-prod

  backend-prod:
    image: ${REGISTRY_IP}:5000/backend:latest
    container_name: backend-prod
    ports:
      - "3001:8080" 
    environment:
      - ENTORNO_NAME=PRODUCCIÓN
      - DB_URL=jdbc:postgresql://db-prod:5432/mydbprod 
      - DB_USER=user
      - DB_PASS=${DB_PASS}
    depends_on:
      - db-prod
    networks:
      - net-prod

networks:
  net-dev:
  net-prod: